#pragma once
#ifndef _CALC_WINDOWPROCEDURE_HPP_INCLUDED_
#define _CALC_WINDOWPROCEDURE_HPP_INCLUDED_

namespace win
{
  extern LRESULT CALLBACK WindowProcedure(HWND, UINT, WPARAM, LPARAM);
}
#endif // _CALC_WINDOWPROCEDURE_HPP_INCLUDED_
