//  SOME COMPILERS PREFER THE USE OF THE PREPROCESSOR: #PRAGMA ONCE
//  SO, WE WILL THROUGH THAT IN FOR FUN
#pragma once
//  SOME COMPILERS PREFER THE PREPROCESSOR STATEMENTS: #IFNDEF (IF Not DEFined) & #DEFINE
#ifndef _CALC_GLOBAL_HPP_INCLUDED_
#define _CALC_GLOBAL_HPP_INCLUDED_


//  HERE, WE ADD MORE STUFF TO THE WIN NAMESPACE.
namespace win
{
  //  C++ HEADER FILES, UNLIKE C HEADER FILES, CAN ONLY CONTAIN DECLARATIONS,
  //  NO DEFINITIONS. DECLARATIONS ARE WHAT YOU SEE BELOW. DEFINITIONS IS WHERE
  //  THE VARIABLES ARE GIVING A VALUE WHEN THEY ARE INITIALIZED.

  //  THE HEADER GUARDS ABOVE DO NOT PREVENT THE C++ COMPILER (AT LEAST GCC, MINGW
  //  ,OR CLANG) FROM INCLUDING THE DECLARATIONS INSIDE THEM. SO, IF THE HEADER IS
  //  INCLUDED IN MULTIPLE CODE FILES, YOU WILL GET MULTIPLE DECLARATION ERROS. TO
  //  PREVENT THIS, YOU NEED TO LET THE COMPILER KNOW THAT THOSE DECLARATIONS ARE
  //  IN THE THE SOURCE CODE FILE OF THE SAME NAME AS THE HEADER FILE. WE DO THIS
  //  BY USING THE "EXTERN" C++ KEYWORD, WHICH MEANS THE FOLLOWING DECLARATIONS HAVE
  //  EXTERNAL LINKAGE AND THE COMPILER ONLY NEEDS TO READ THE DECLARATIONS AND/OR
  //  DEFINITIONS FROM THE SOURCE CODE WITH THE SAME FILE NAME AS THE HEADER FILE.

  //  WITHOUT THE "EXTERN' KEYWORD, THE COMPILER ADDS THE DECLARATIONS EVERY TIME
  //  THE HEADER FILE IS INCLUDED IN CODE FILES, WHICH CAN CAUSE MULTIPLE DECLARATION
  //  ERRORS. WHILE THE HEADER FILE CAN BE INCLUDED MULTIPLE TIMES IN A PROJECT, THE
  //  COMPILER DOES NOT INCLUDE THE CODE FILES OF THE SAME NAME AS THE HEADER FILE
  //  MORE THEN ONCE. THIS IS WHY THE "EXTERN" KEYWORD IS VERY IMPORTANT TO USE IN
  //  THE HEADER FILES.

  //  EXTERN:
  //  https://docs.microsoft.com/en-us/cpp/cpp/extern-cpp?view=msvc-160

  //  TRANSALTION UNITS AND LINKAGE:
  //  https://docs.microsoft.com/en-us/cpp/cpp/program-and-linkage-cpp?view=msvc-160

  extern HINSTANCE AppInstanceHandle;
  extern HWND      WindowHandle;
  extern int       CommandShow;
  extern LPSTR     CommandLineString;
  extern RECT      WindowClientAreaSize;
  extern RECT      WindowTotalSize;
}

#endif // _CALC_GLOBAL_HPP_INCLUDED_
